# 서비스 경로 설정
paths:
  assets_path: "/app/service_assets"
  annoy_index: "music_annoy.ann"
  faiss_index: "vector_db.index"
  deepfm_model: "deepfm_model.pt"
  scaler: "scaler.pkl"
  encoders: "encoders.pkl"
  item_metadata: "item_meta.csv" # 곡 이름, 아티스트 정보용

# 추천 로직 파라미터
recommendation:
  # 슬라이더 기반 (Annoy)
  slider_top_k: 20
  
  # 최종 추천 (Faiss + DeepFM)
  retrieval_top_k: 2000       # Faiss에서 뽑을 후보군 수 (추출)
  rerank_top_k: 10           # DeepFM이 최종적으로 내보낼 수 (리랭킹)

# 모델 상세 설정
model:
  embedding_dim: 64
  hidden_layers: [256, 128, 64]
  dropout: 0.4
  continuous_features: ['acousticness', 'valence', 'energy', 'danceability', 'instrumentalness', 'loudness', 'speechiness', 'tempo', 'popularity']